name: Close invalid issues
on:
  issues:
    types: [opened]

jobs:
  close-issues:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.body, 'Error Compiling Codes') == true
    permissions:
      issues: write
    steps:
      - name: Detect code from mod
        uses: KyoriPowered/action-regex-match@v4
        id: regex-match
        with:
          text: ${{ github.event.issue.body }}
          regex: '-\s+?(?<mod>.+?)\\(?<code>.+)'

      - name: Create comment
        uses: actions-cool/issues-helper@v3
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          actions: 'create-comment'
          body: |
            This issue was caused by a mod and not by a code from this repository.

            As a quick troubleshoot, make sure your codes are up to date by going to the Codes tab and clicking Download/Update Community Codes.

            If this issue still persists after that, then contact the author(s) of the mod.

      - name: Add invalid label
        uses: actions-cool/issues-helper@v3
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          actions: 'add-labels'
          labels: 'invalid'

      - name: Close issue
        uses: actions-cool/issues-helper@v3
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          actions: 'close-issue'

      - name: Lock issue
        uses: actions-cool/issues-helper@v3
        if: ${{ steps.regex-match.outputs.match != '' }}
        with:
          actions: 'lock-issue'
